project_name        = "dev-app"
aws_region          = "us-east-1"
vpc_cidr           = "10.1.0.0/16"
public_subnet_cidrs = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidrs = ["10.1.3.0/24", "10.1.4.0/24"]
availability_zones  = ["us-east-1a"]
ami_id             = "ami-0c02fb55956c7d316"
instance_type      = "t3.micro"
key_name           = "my-key-pair"
desired_capacity   = 1
max_size           = 2
min_size           = 1
db_name           = "devdb"
db_username       = "admin"
db_password       = "DevPassword123!"
db_instance_class = "db.t3.micro"
db_allocated_storage = 10
db_multi_az       = false