plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: "production-app"
  instance-state-name: running
keyed_groups:
  - key: tags
    prefix: tag
  - key: placement.region
    prefix: aws_region
compose:
  ansible_user: "ec2-user"
  ansible_ssh_private_key_file: "~/.ssh/my-key-pair.pem"